CREATE TABLE `Finance` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`status` VARCHAR(255) NOT NULL,
	`value` DOUBLE NOT NULL
);